# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-y23tTTs_aMjSYwPa3Fk8Ywz8H8ZUgl

#**GRADIO**
"""

import gradio as gr
import joblib as jb

def predict(sex, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status):
    model = jb.load('model.pkl')
    sex = str(sex)
    age = int(age)
    hypertension = str(hypertension)
    heart_disease = str(heart_disease)
    ever_married = str(ever_married)
    work_type = str(work_type)
    Residence_type = int(Residence_type)
    avg_glucose_level   = float(avg_glucose_level  )
    bmi = float(bmi)
    smoking_status = str(smoking_status)


    p = model.predict({{sex, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status}})[0]

    return {"Não terá AVC": p[0], "Terá AVC": p[1]}

demo = gr.Interface(fn=predict,
                   inputs=[gr.Dropdown(choices=["female", "male"], type="index"),
                          "number",
                           gr.Dropdown(choices=["Não Hipertenso", "Hipertenso"], type="index"),
                           gr.Dropdown(choices=["Não doença cardíaca", "Possui doença cardíaca"], type="index"),
                           gr.Dropdown(choices=["Não casado(a)", "Casado(a)"], type="index"),
                           gr.Dropdown(choices=["Nunca trabalhou", "filhos", "Emprego público", "Autônomo", "Privado"], type="index"),
                           gr.Dropdown(choices=["Rural", "Urbana"], type="index"),
                           "number",
                           "number",
                           gr.Dropdown(choices=["Nunca fumou", "Fuma"], type="index"),
                          ],
                    outputs="label")


demo.launch()